# Generated by Django 4.0.1 on 2022-01-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['status']},
        ),
        migrations.AddField(
            model_name='instance',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('running_test', 'running_test'), ('terminated', 'terminated')], default='idle', max_length=30),
        ),
    ]
